# PyTorch

In this lesson we'll learn about PyTorch which is a machine learning library used to build dynamic neural networks. We'll learn about the basics, like creating and using Tensors, in this lesson but we'll be making models with it in the next lesson.

<img src="figures/pytorch.png" width=300>

# Tensor basics

In [1]:
# Let's make sure the libraries are installed
#!pip install numpy
#!pip install torch

# Now import the libraries
import numpy as np
import torch

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Creating a zero tensor
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[1.3711e-14, 6.4076e+07, 2.0706e-19, 7.3909e+22],
        [2.4176e-12, 1.1625e+33, 8.9605e-01, 1.1632e+33],
        [5.6003e-02, 7.0374e+22, 5.7453e-44, 0.0000e+00]])


In [3]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution (rand(2,3) -> uniform distribution)
print (x)

tensor([[ 1.7417,  0.6416,  1.1948],
        [-0.8084,  0.9487,  0.1214]])


In [4]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# NumPy array → Tensor
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.4993, 0.0948, 0.9342],
        [0.6652, 0.6913, 0.9621]], dtype=torch.float64)


In [7]:
# Changing tensor type
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor operations

In [8]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.6505,  3.0682,  1.4773],
        [-1.6490, -0.3232,  0.4954]])


In [9]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[1.7608, 0.5642],
        [0.4580, 2.6860]])


In [10]:
# Transpose
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.8471,  1.5471, -0.6370],
        [ 0.3827,  0.1994,  0.4496]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.8471,  0.3827],
        [ 1.5471,  0.1994],
        [-0.6370,  0.4496]])


In [11]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.8471,  1.5471],
        [-0.6370,  0.3827],
        [ 0.1994,  0.4496]])


In [12]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [13]:
# Dimensional operations
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # add each row's value for every column
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # add each columns's value for every row
print("Values: \n{}".format(z))

Values: 
tensor([[ 0.0299,  0.2626, -1.7405],
        [ 0.3509, -1.0229, -1.3241]])
Values: 
tensor([ 0.3808, -0.7603, -3.0646])
Values: 
tensor([-1.4481, -1.9961])


# Indexing, Splicing and Joining

In [14]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[-0.3381, -0.8424, -0.8640,  0.4485],
        [ 0.6683, -0.1577,  2.2624, -0.6932],
        [ 0.3293, -0.9860, -0.2147, -0.7992]])
x[:1]: 
tensor([[-0.3381, -0.8424, -0.8640,  0.4485]])
x[:1, 1:3]: 
tensor([[-0.8424, -0.8640]])


In [15]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1)
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[ 0.3777, -1.3931,  0.1461],
        [ 0.5323, -0.0325, -0.3534]])
Values: 
tensor([[ 0.3777,  0.1461],
        [ 0.5323, -0.3534]])
Values: 
tensor([ 0.3777, -0.3534])


In [16]:
# Concatenation
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print("Values: \n{}".format(y))

Values: 
tensor([[ 0.7884, -0.0234,  1.0082],
        [-1.0683,  0.6639, -0.4388]])
Values: 
tensor([[ 0.7884, -0.0234,  1.0082],
        [-1.0683,  0.6639, -0.4388],
        [ 0.7884, -0.0234,  1.0082],
        [-1.0683,  0.6639, -0.4388]])


# Gradients

In [17]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.1176, 0.1948, 0.5465, 0.1160],
        [0.6329, 0.3449, 0.2547, 0.1937],
        [0.6376, 0.4862, 0.9722, 0.3899]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [18]:
# Is CUDA available?
print (torch.cuda.is_available())

False


If the code above returns False, then go to `Runtime` → `Change runtime type` and select `GPU` under `Hardware accelerator`. 

In [19]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [ ]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))